import { NextResponse } from 'next/server'

const OPENROUTER_API_KEY = process.env.OPENROUTER_API_KEY
const OPENROUTER_API_URL = 'https://openrouter.ai/api/v1/chat/completions'

export async function POST(request: Request) {
  const { appName, htmlCode } = await request.json()
  
  if (!OPENROUTER_API_KEY) {
    console.error('OPENROUTER_API_KEY is not set')
    return NextResponse.json(
      { error: 'API key not configured' },
      { status: 500 }
    )
  }

  if (!htmlCode) {
    return NextResponse.json(
      { error: 'HTML code is required' },
      { status: 400 }
    )
  }

  const prompt = `Analyze the following HTML code for a "${appName}" app and provide a detailed technical description of how it functions.

Focus on:
- The technical implementation details of each feature
- How the HTML structure is organized
- CSS styling techniques and layout methods used
- JavaScript functionality and how it's implemented
- Event handling mechanisms
- Data storage and state management approaches
- Any specific algorithms or patterns used
- How the UI is rendered and updated
- Responsive design implementation
- Technical choices made in the implementation

Return a well-formatted, readable text description (not code) that explains the technical workings of this application. Use clear sections, paragraphs, and technical terminology.

HTML code:
\`\`\`html
${htmlCode}
\`\`\`

Provide a comprehensive technical analysis.`

  try {
    const response = await fetch(OPENROUTER_API_URL, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${OPENROUTER_API_KEY}`,
        'HTTP-Referer': process.env.NEXT_PUBLIC_APP_URL || 'http://localhost:3000',
        'X-Title': 'VibePhone'
      },
      body: JSON.stringify({
        model: 'google/gemini-3-flash-preview',
        messages: [
          {
            role: 'system',
            content: 'You are a technical documentation expert who analyzes code and explains how it works. Provide clear, detailed technical descriptions focusing on implementation details, architecture, and how features are technically implemented.'
          },
          {
            role: 'user',
            content: prompt
          }
        ],
        temperature: 0.7,
        max_tokens: 2000
      })
    })

    if (!response.ok) {
      let errorMessage = `API request failed: ${response.statusText}`
      try {
        const errorData = await response.json()
        errorMessage = errorData.error?.message || errorData.error || errorMessage
      } catch {
        console.error('OpenRouter API error (non-JSON):', response.status)
      }
      
      if (response.status === 401) {
        errorMessage = 'Invalid API key. Please check your OpenRouter API key.'
      } else if (response.status === 429) {
        errorMessage = 'Rate limit exceeded. Please try again in a moment.'
      } else if (response.status === 402) {
        errorMessage = 'Insufficient credits. Please check your OpenRouter account.'
      }
      
      console.error('OpenRouter API error:', response.status, errorMessage)
      return NextResponse.json(
        { error: errorMessage },
        { status: response.status }
      )
    }

    let data
    try {
      data = await response.json()
    } catch (error) {
      console.error('Failed to parse API response:', error)
      return NextResponse.json(
        { error: 'Invalid response from API' },
        { status: 500 }
      )
    }

    const description = data.choices?.[0]?.message?.content?.trim()

    if (!description) {
      return NextResponse.json(
        { error: 'No description generated by AI' },
        { status: 500 }
      )
    }

    return NextResponse.json({ description })

  } catch (error) {
    console.error('Error analyzing code:', error)
    return NextResponse.json(
      { error: 'Failed to analyze code', details: error instanceof Error ? error.message : 'Unknown error' },
      { status: 500 }
    )
  }
}

