import { NextResponse } from 'next/server'

const OPENROUTER_API_KEY = process.env.OPENROUTER_API_KEY
const OPENROUTER_API_URL = 'https://openrouter.ai/api/v1/chat/completions'

export async function POST(request: Request) {
  const { appName, currentHtml } = await request.json()
  
  if (!OPENROUTER_API_KEY) {
    console.error('OPENROUTER_API_KEY is not set')
    return NextResponse.json(
      { error: 'API key not configured' },
      { status: 500 }
    )
  }

  if (!currentHtml) {
    return NextResponse.json(
      { error: 'Current HTML is required' },
      { status: 400 }
    )
  }

  const prompt = `Enhance this "${appName}" app by adding more advanced features and functionality. The current app is functional, but you should add:

- Additional useful features that complement the core functionality
- Enhanced user experience improvements
- More sophisticated functionality
- Better UI/UX polish
- Advanced features that make the app more powerful

Keep all existing functionality intact while adding new features on top. Make the app more feature-rich and impressive.

Current HTML code:
\`\`\`html
${currentHtml}
\`\`\`

Requirements:
- Return ONLY the complete, enhanced HTML code
- Keep it as a single-file HTML application (all CSS in <style> tags, all JavaScript in <script> tags)
- Ensure all existing features still work
- Add new features that enhance the app
- Maintain the same app concept and improve upon it
- Make the UI more polished and feature-rich
- Ensure the code works in a sandboxed iframe

Generate ONLY the HTML code. Do not include any markdown formatting, code blocks, or explanations. Start with <!DOCTYPE html> and end with </html>.`

  try {
    const response = await fetch(OPENROUTER_API_URL, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${OPENROUTER_API_KEY}`,
        'HTTP-Referer': process.env.NEXT_PUBLIC_APP_URL || 'http://localhost:3000',
        'X-Title': 'VibePhone'
      },
      body: JSON.stringify({
        model: 'google/gemini-3-flash-preview',
        messages: [
          {
            role: 'system',
            content: 'You are an expert web developer who enhances existing apps by adding new features and improving functionality. Always return only valid HTML code, no markdown or explanations.'
          },
          {
            role: 'user',
            content: prompt
          }
        ],
        temperature: 0.7,
        max_tokens: 16000
      })
    })

    if (!response.ok) {
      let errorMessage = `API request failed: ${response.statusText}`
      try {
        const errorData = await response.json()
        errorMessage = errorData.error?.message || errorData.error || errorMessage
      } catch {
        console.error('OpenRouter API error (non-JSON):', response.status)
      }
      
      if (response.status === 401) {
        errorMessage = 'Invalid API key. Please check your OpenRouter API key.'
      } else if (response.status === 429) {
        errorMessage = 'Rate limit exceeded. Please try again in a moment.'
      } else if (response.status === 402) {
        errorMessage = 'Insufficient credits. Please check your OpenRouter account.'
      }
      
      console.error('OpenRouter API error:', response.status, errorMessage)
      return NextResponse.json(
        { error: errorMessage },
        { status: response.status }
      )
    }

    let data
    try {
      data = await response.json()
    } catch (error) {
      console.error('Failed to parse API response:', error)
      return NextResponse.json(
        { error: 'Invalid response from API' },
        { status: 500 }
      )
    }

    const choice = data.choices?.[0]
    const htmlContent = choice?.message?.content?.trim()
    const finishReason = choice?.finish_reason

    if (!htmlContent) {
      return NextResponse.json(
        { error: 'No content generated by AI' },
        { status: 500 }
      )
    }

    // Check if response was truncated
    if (finishReason === 'length') {
      console.warn('API response was truncated due to token limit')
      return NextResponse.json(
        { error: 'Response was too long and got truncated. Please try with a smaller app or increase token limit.' },
        { status: 500 }
      )
    }

    // Clean up the response - remove markdown code blocks if present
    let html = htmlContent
      .replace(/^```html\n?/i, '')
      .replace(/^```\n?/i, '')
      .replace(/```\n?$/i, '')
      .trim()

    // Ensure it starts with <!DOCTYPE or <html
    if (!html.startsWith('<!') && !html.startsWith('<html')) {
      html = `<!DOCTYPE html>\n${html}`
    }

    // Validate HTML is complete - must have closing </html> tag
    const htmlLower = html.toLowerCase()
    const hasClosingHtml = htmlLower.includes('</html>')
    
    // If HTML has any opening HTML structure, it must have a closing tag
    if ((htmlLower.includes('<!doctype') || htmlLower.includes('<html')) && !hasClosingHtml) {
      console.error('HTML is incomplete - missing closing </html> tag')
      return NextResponse.json(
        { error: 'Generated HTML is incomplete and missing closing tags. The response may have been truncated.' },
        { status: 500 }
      )
    }

    return NextResponse.json({ html })

  } catch (error) {
    console.error('Error enhancing app:', error)
    return NextResponse.json(
      { error: 'Failed to enhance app', details: error instanceof Error ? error.message : 'Unknown error' },
      { status: 500 }
    )
  }
}

